os: osx

language: java 
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.cache"
after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B
notifications:
  email:
    recipients:
    - jmscomponents@gmail.com
    on_success: always
    on_failure: always