sudo: false

language: java 
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.cache"
after_success:
  - mvn deploy -DskipTests=true -B -Pbintray
notifications:
  email:
    recipients:
    - jmscomponents@gmail.com
    on_success: always
    on_failure: always